### ISSUE TITLE
Creation of CI setup with Github Actions

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Fi1e-EncRypt0R#10]
Creation of integrated builds to verify the system integrity

**Comment by Yagueteiro** [comment]
Hi, I would be interested in working on this issue. What do you exactly want it to do?

**Comment by rexdivakar** [comment]
Issue assigned to @Yagueteiro 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Comment by Yagueteiro** [comment]
> Feel free to drop in https://discord.gg/59TDJgt

Sorry, the link says it has expired

**Comment by rexdivakar** [comment]
Sorry to hear that @Yagueteiro  please use the below link,

https://discord.gg/e47wmTW
