### ISSUE TITLE
Upgrading encryption protocol

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Fi1e-EncRypt0R#11]
As of now we use AES-Advanced encryption system to encrypt the files but expecting some new salts to add in features for the system.

**Comment by SanchitJain123** [comment]
@rexdivakar Do you want to add other algorithms other than AES? If yes, any suggestions for this

**Comment by rexdivakar** [comment]
I believe we can add asymmetric RSA encryption

**Comment by SanchitJain123** [comment]
Sure we can. I would like to work on this then

**Comment by rexdivakar** [comment]
Issue assigned to @SanchitJain123 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding

**Comment by SanchitJain123** [comment]
@rexdivakar RSA is not suitable to encrypt larger files so it is recommended to encrypt AES encryption key with RSA rather than the file content. Should I proceed with that?

**Comment by rexdivakar** [comment]
Well we need a asymmetric method of encryption got any ideas on that ? @SanchitJain123

**Comment by SanchitJain123** [comment]
This will be asymmetric in the sense that the AES encryption key will be encrypted through RSA (asymmetric encryption), while the data will be encrypted through symmetric one. Kinda hybrid encryption :). Also, I have read various sources on the stack as well all are suggesting this. But if we would like that the data is also encrypted through the asymmetric methods then we will have to maybe encrypt chunks of data through the same public key and encrypt the whole file. The first approach will be faster and the second approach will be slower. @rexdivakar

**Comment by rexdivakar** [comment]
right now we need a asymmetric method so we can share the keys to the another user via ssh so others can use it @SanchitJain123 
Do u think that could be done ?

**Comment by SanchitJain123** [comment]
Yes, the procedure would be this,
1. We will generate the AES encryption key and encrypt it through asymmetric RSA. New public and private keys will be generated through this.
2. We will save privateKey along with the encrypted AES encryption key in a dedicated file.  (let's say this file is named `key.pem`).
3. Then the user can send the `key.pem` file through ssh connection to another user and save it along the encrypted file/folder or the user can specify the path for the same in the command line.
4. Then, the user will have a decrypted file/folder using the same using our program.

**Comment by rexdivakar** [comment]
yup, exactly what i need in @SanchitJain123

**Comment by SanchitJain123** [comment]
I'll start implementing this then.

**Comment by rexdivakar** [comment]
yes go ahead @SanchitJain123

**Comment by rexdivakar** [comment]
Hey @SanchitJain123  ur decryption is failing for folders, can u please check it !

**Comment by SanchitJain123** [comment]
@rexdivakar sure will check it if there is some issue. When I tried it, it was working fine.

**Comment by rexdivakar** [comment]
please ping me @SanchitJain123  over discord username: root#5998 
https://discord.gg/e47wmTW
