### ISSUE TITLE
Create a executable file to run on Windows

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Fi1e-EncRypt0R#7]
Existing setup of creating exe files fails on executing on certain version of windows, fix it

**Comment by michaelchristopher-ui** [comment]
I would like to try to work on this. What version of windows did the exe not work at?

**Comment by rexdivakar** [comment]
Windows 10 and windows 8.1

**Comment by rexdivakar** [comment]
Issue assigned to @michaelchristopher-ui 
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/59TDJgt

**Comment by rexdivakar** [comment]
zip the .exe file before pushing it to the repo @michaelchristopher-ui

**Comment by rexdivakar** [comment]
Un assigning u since i haven't got any updates yet !! @michaelchristopher-ui

**Comment by rexdivakar** [comment]
Issue assigned and fixed by @Yagueteiro

**Comment by rexdivakar** [comment]
🌟 Star it 🍴Fork it 🤝 Contribute to it!
Happy Coding..

Feel free to drop in https://discord.gg/e47wmTW

**Comment by rexdivakar** [comment]
#18
