### ISSUE TITLE
Creating proper documentation

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Fi1e-EncRypt0R#9]

**Comment by Tawishi** [comment]
I would like to work on this issue @rexdivakar .

**Comment by Tawishi** [comment]
ANy specific things to be included or kept in mind for documentation @rexdivakar ?

**Comment by rexdivakar** [comment]
You can add a README.md file, requirements.txt and add in the work structure

**Comment by Tawishi** [comment]
> You can add a README.md file, requirements.txt and add in the work structure

What do you mean by work structure ?

**Comment by rexdivakar** [comment]
How AES works and how we are using it to encrypt the files

**Comment by rexdivakar** [comment]
Join in to discuss more https://discord.gg/3VWffB

**Comment by Tawishi** [comment]
During file decryption, even after entering the key, it shows Decryption failed.
_Images attached below for reference_

![Screenshot from 2020-09-28 20-46-38](https://user-images.githubusercontent.com/55306738/94452052-bebdd480-01cc-11eb-90e2-5a6759303208.png)

![Screenshot from 2020-09-28 20-46-32](https://user-images.githubusercontent.com/55306738/94451584-32abad00-01cc-11eb-8106-a13ec398ad9e.png)

**Comment by Tawishi** [comment]
In **folder encryption**, if the folder has files in it, the code runs into an error. Otherwise, it runs just fine.
_Image attached below for reference_

![Screenshot from 2020-09-28 21-07-18](https://user-images.githubusercontent.com/55306738/94453978-f463bd00-01ce-11eb-8b4e-329558d34e58.png)

**Comment by Tawishi** [comment]
@rexdivakar please help to resolve these errors! Or if I am doing something wrong so that I can include the same in the readme .

**Comment by rexdivakar** [comment]
It is unable to find the file due to escape sequence in the file path u may resolve it or raise a Issue and work on @Tawishi

**Comment by Tawishi** [comment]
> During file decryption, even after entering the key, it shows Decryption failed.
> _Images attached below for reference_
> 
> ![Screenshot from 2020-09-28 20-46-38](https://user-images.githubusercontent.com/55306738/94452052-bebdd480-01cc-11eb-90e2-5a6759303208.png)
> 
> ![Screenshot from 2020-09-28 20-46-32](https://user-images.githubusercontent.com/55306738/94451584-32abad00-01cc-11eb-8106-a13ec398ad9e.png)

Why is this happening?

**Comment by rexdivakar** [comment]
The issue has been patched u can proceed now @Tawishi 

Problem (IO file creation error)

**Comment by rexdivakar** [comment]
The issue has been patched u can proceed now @Tawishi 

Problem (IO file creation error)

**Comment by rexdivakar** [comment]
hey @Tawishi  can u please ping me https://discord.gg/e47wmTW

**Comment by Tawishi** [comment]
> hey @Tawishi can u please ping me https://discord.gg/e47wmTW

Your username and tag ?

**Comment by rexdivakar** [comment]
root#5998
